# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Climanager < Formula
  desc ""
  homepage "https://github.com/darrenleak/climanager"
  version "0.1.9"

  on_macos do
    url "https://github.com/darrenleak/climanager/releases/download/v0.1.9/climanager_0.1.9_darwin_all.tar.gz"
    sha256 "fd3928761925564178dbb42ad8b9e507cb86bfa079cf1c01faf3d82af6b6505d"

    def install
      bin.install "climanager"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/darrenleak/climanager/releases/download/v0.1.9/climanager_0.1.9_linux_amd64.tar.gz"
      sha256 "7b9f9e8569fd9cb4babaa460f46a770ffbc37ad06777b5e0211be65e5e13daba"

      def install
        bin.install "climanager"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/darrenleak/climanager/releases/download/v0.1.9/climanager_0.1.9_linux_arm64.tar.gz"
      sha256 "7ef9ec0d30245a7c9f4026a4c910dd0bc35adad71f075a06feeada37cef5bcf1"

      def install
        bin.install "climanager"
      end
    end
  end
end
