# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Climanager < Formula
  desc ""
  homepage "https://github.com/darrenleak/climanager"
  version "0.1.11"

  on_macos do
    url "https://github.com/darrenleak/climanager/releases/download/v0.1.11/climanager_0.1.11_darwin_all.tar.gz"
    sha256 "f0ce2d9dc0436c0dd13d4cffa25459bde1b49fb88b0f21bfc27a05bfe3fb0843"

    def install
      bin.install "climanager"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/darrenleak/climanager/releases/download/v0.1.11/climanager_0.1.11_linux_arm64.tar.gz"
      sha256 "79a6945650d7571ab032a1d680f18eecb2f19dd6c6bcc8885cd29ef009386919"

      def install
        bin.install "climanager"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/darrenleak/climanager/releases/download/v0.1.11/climanager_0.1.11_linux_amd64.tar.gz"
      sha256 "98d44a8fa9f21b6e5f560a6a8d298674fff33e89478cf9f65f4ebe23a89cb0d1"

      def install
        bin.install "climanager"
      end
    end
  end
end
